import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Affiliate Disclosure — Jamie's Finance",
  description: "How affiliate links, friend referral links, and partnerships work on Jamie's Finance.",
};

export default function AffiliateDisclosurePage() {
  return (
    <>
      <section className="pt-32 pb-20 px-6" style={{ background: "var(--card)" }}>
        <div className="max-w-3xl mx-auto">
          <div className="flex flex-wrap items-center gap-3 mb-8">
            <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-[0.6875rem] font-bold uppercase tracking-widest border"
              style={{ background: "rgba(0,0,0,0.05)", color: "var(--ink-60)", borderColor: "var(--border)" }}>
              Legal
            </span>
          </div>
          <h1 className="font-display text-5xl sm:text-6xl leading-none mb-6" style={{ color: "var(--foreground)" }}>
            Affiliate<br />Disclosure
          </h1>
          <p className="text-lg prose-body">
            Last updated: April 2026
          </p>
        </div>
      </section>

      <section className="py-16 px-6" style={{ background: "var(--background)" }}>
        <div className="max-w-3xl mx-auto space-y-12">

          {/* Overview */}
          <div>
            <h2 className="font-display text-2xl sm:text-3xl mb-5" style={{ color: "var(--foreground)" }}>
              Overview
            </h2>
            <div className="space-y-4 text-sm" style={{ color: "var(--ink-60)", lineHeight: 1.85 }}>
              <p>
                Jamie&apos;s Finance is committed to full transparency about how links and recommendations on this website work. Some links on this website are <strong style={{ color: "var(--foreground)" }}>affiliate links</strong> or <strong style={{ color: "var(--foreground)" }}>friend referral links</strong>. This means that if you click a link and sign up for or purchase a product, Jamie&apos;s Finance may receive a commission, reward, or incentive — at <strong style={{ color: "var(--foreground)" }}>no additional cost to you</strong>.
              </p>
              <p>
                In some cases, clicking through a referral link may also result in <strong style={{ color: "var(--foreground)" }}>additional benefits for you</strong> — such as a welcome bonus, extra points, or a cashback reward. Where this is the case, it is noted alongside the link.
              </p>
            </div>
          </div>

          {/* Types of links */}
          <div>
            <h2 className="font-display text-2xl sm:text-3xl mb-5" style={{ color: "var(--foreground)" }}>
              Types of Links on This Site
            </h2>
            <div className="space-y-5">
              {[
                {
                  title: "Affiliate Programme Links",
                  body: "Some links are through formal affiliate programmes — platforms where Jamie's Finance is registered as an affiliate and earns a commission when you sign up or make a qualifying purchase. An example of this is TopCashback, where Jamie's Finance participates in their referral programme.",
                },
                {
                  title: "Friend Referral Links",
                  body: "Some links are personal friend referral links — not a formal commercial partnership or sponsored relationship with the brand. For example, the American Express referral links on this website are personal friend links generated by Jamie's own Amex card accounts. Using these links may earn Jamie a small, capped number of reward points per referral, and may earn you a welcome bonus. Jamie is not employed by, sponsored by, or in a commercial agreement with American Express.",
                },
                {
                  title: "Non-Affiliate Links",
                  body: "Many links on this website are plain links with no affiliate relationship at all — included purely because the content is useful or relevant. The absence of an affiliate relationship does not mean a product is better or worse than one with an affiliate link.",
                },
              ].map((item) => (
                <div key={item.title} className="rounded-2xl p-6 border" style={{ background: "var(--card)", borderColor: "var(--border)" }}>
                  <p className="font-semibold mb-2" style={{ color: "var(--foreground)" }}>{item.title}</p>
                  <p className="text-sm" style={{ color: "var(--ink-60)", lineHeight: 1.85 }}>{item.body}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Current affiliate relationships */}
          <div>
            <h2 className="font-display text-2xl sm:text-3xl mb-5" style={{ color: "var(--foreground)" }}>
              Current Affiliate & Referral Relationships
            </h2>
            <div className="space-y-4 text-sm" style={{ color: "var(--ink-60)", lineHeight: 1.85 }}>
              <p>The following relationships are currently active on this website:</p>
              <div className="rounded-2xl overflow-hidden border" style={{ borderColor: "var(--border)" }}>
                {[
                  {
                    platform: "TopCashback",
                    type: "Affiliate Programme",
                    benefit: "Welcome bonus for new sign-ups; commission to Jamie's Finance",
                    notes: "Formal affiliate programme",
                  },
                  {
                    platform: "American Express (BA Card, Nectar Card, Gold Card)",
                    type: "Friend Referral Links",
                    benefit: "Possible welcome bonus for you; capped referral points for Jamie",
                    notes: "Personal referral links only — no commercial partnership with Amex",
                  },
                ].map((row, i) => (
                  <div key={row.platform} className="grid sm:grid-cols-[1fr_auto] gap-3 p-5"
                    style={{ background: i % 2 === 0 ? "var(--card)" : "var(--muted)", borderTop: i > 0 ? "1px solid var(--border)" : "none" }}>
                    <div>
                      <p className="font-semibold text-sm mb-0.5" style={{ color: "var(--foreground)" }}>{row.platform}</p>
                      <p className="text-xs mb-1" style={{ color: "var(--ink-40)" }}>{row.type}</p>
                      <p className="text-xs" style={{ color: "var(--ink-60)" }}>{row.benefit}</p>
                    </div>
                    <span className="self-start inline-flex items-center px-2.5 py-1 rounded-full text-[0.6875rem] font-bold uppercase tracking-widest border whitespace-nowrap"
                      style={{ background: "var(--muted)", color: "var(--ink-40)", borderColor: "var(--border)" }}>
                      {row.notes}
                    </span>
                  </div>
                ))}
              </div>
              <p>
                This list will be kept up to date as new relationships are added or existing ones change.
              </p>
            </div>
          </div>

          {/* Editorial independence */}
          <div>
            <h2 className="font-display text-2xl sm:text-3xl mb-5" style={{ color: "var(--foreground)" }}>
              Editorial Independence
            </h2>
            <div className="space-y-4 text-sm" style={{ color: "var(--ink-60)", lineHeight: 1.85 }}>
              <p>
                The existence of an affiliate or referral relationship does <strong style={{ color: "var(--foreground)" }}>not influence the editorial opinions</strong> expressed on this website. Reviews, scores, and recommendations reflect honest personal opinions based on real usage and research.
              </p>
              <p>
                Products are reviewed whether or not an affiliate link exists. Where a product receives a negative review (such as Aqua or the Barclaycard Avios), that review stands regardless of whether a referral link is available. Jamie&apos;s Finance does not accept payment to feature, promote, or positively review any product.
              </p>
            </div>
          </div>

          {/* Consumer Rights / ASA compliance */}
          <div>
            <h2 className="font-display text-2xl sm:text-3xl mb-5" style={{ color: "var(--foreground)" }}>
              Compliance with UK Advertising Standards
            </h2>
            <p className="text-sm" style={{ color: "var(--ink-60)", lineHeight: 1.85 }}>
              In accordance with the UK Advertising Standards Authority (ASA) and Committee of Advertising Practice (CAP) guidelines, affiliate and referral content on this website is clearly disclosed. Where individual links are affiliate links, this is indicated in context. This disclosure page applies site-wide and is linked from all pages containing affiliate or referral links.
            </p>
          </div>

          {/* Contact */}
          <div className="rounded-2xl p-6 border" style={{ background: "var(--muted)", borderColor: "var(--border)" }}>
            <p className="font-semibold mb-2" style={{ color: "var(--foreground)" }}>Questions?</p>
            <p className="text-sm" style={{ color: "var(--ink-60)", lineHeight: 1.7 }}>
              If you have any questions about affiliate relationships on this website:{" "}
              <a href="mailto:jamie@jamiesfinance.uk" className="font-semibold underline" style={{ color: "var(--foreground)" }}>jamie@jamiesfinance.uk</a>
            </p>
            <p className="text-sm mt-3" style={{ color: "var(--ink-60)", lineHeight: 1.7 }}>
              See also: <Link href="/disclaimer" className="underline" style={{ color: "var(--foreground)" }}>Full Disclaimer</Link>
            </p>
          </div>

        </div>
      </section>
    </>
  );
}
